name: Build PNGs from SVGs
on:
  push:
    branches: [ main, demo-artifacts ]
  workflow_dispatch: {}
jobs:
  png:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g @resvg/resvg-js-cli
      - run: |
          shopt -s nullglob
          for f in docs/assets/*.svg; do
            out="${f%.svg}.png"
            # positional output syntax works across versions:
            resvg-js "$f" "$out" -w 2000 || resvg "$f" "$out" -w 2000
            echo "Wrote $out"
          done
      - name: Commit PNGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/assets/*.png || true
          git commit -m "ci: add/update PNG exports" || echo "No changes"
          git push
